[project]
name = "emociones"
version = "1.0.0"
description = "Emociones (Fotos y Videos)"
authors = [
    { name = "José Mª Barreiro López", email = "jmbarreiroicm@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["PyQt5"]


# Configuración del sistema de construcción
[build-system]
requires = ["pyinstaller","setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# Configuración adicional para setuptools
[tool.setuptools]
packages = ["emociones"]
package-dir = {"" = "src"}

[tool.pyinstaller]
entry-point = "src/app.py"
output-name = "emociones"
add-data = ["data/preferences.json=data"]